config/routes.rb
Judi::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tasks do
    member do
      get 'details'
    end
  end
  
  resources :projects
  resources :documents

  root to: "projects#index"

end

app/models/document.rb
class Document < ActiveRecord::Base

  has_attached_file :attachment, :preserve_files => true

  belongs_to  :project
  belongs_to  :task


end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to  :task
  belongs_to  :project

end

app/models/project.rb
class Project < ActiveRecord::Base

  attr_accessible :title, :description, :user_id

  has_many :notes

  has_many :tasks

  has_many :documents

  belongs_to :user

  def have_tasks?
    if tasks.count > 0
      return true
    end
    false
  end

  def have_documents?
    if documents.count > 0
      return true
    end
    false
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  extend Enumerize

  attr_accessible :title, :description, :project_id, :status, :priority

  enumerize :status, :in => {
    :created => 0, 
    :working => 1, 
    :waiting => 2, 
    :paused => 3, 
    :stopped => 4, 
    :finished => 5
    }, default: :created, scope: true

  enumerize :priority, :in => {
    :urgent => 0, 
    :highest => 1, 
    :high => 2, 
    :medium => 3, 
    :low => 4, 
    :lowest => 5,
    :no => 6
    }, default: :no, scope: true
  
  belongs_to :project

  has_many :notes

  has_many  :documents


  def have_documents?
    if documents.count > 0
      return true
    end
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :projects

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(#name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  layout "manager"

  def index
    @projects = current_user.projects.order('created_at')
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @project = Project.new(:user_id => params[:user_id])

    respond_to do |format|
      format.html { render :layout => !request.xhr? }
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
    render :layout => !request.xhr?
  end

  def create
    @project= Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)

      @requested_info = request.env["omniauth.auth"].extra.raw_info

      #raise @requested_info.to_yaml

      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"

        #updates the db info
        @user.name = @requested_info.name
        @user.first_name = @requested_info.given_name
        @user.last_name = @requested_info.family_name
        @user.picture = @requested_info.picture
        @user.gender = @requested_info.gender

        #raise @user.to_yaml
        
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for(@document) do |f| %>  
  <%= f.hidden_field :project_id %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "span4"%>
  </div>
  <br />
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "span4", :rows => 3 %>
  </div>
  <br />
  <div class="field">
    <%= f.file_field :attachment%>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/index.html.erb
<div class="well" style="padding: 8px 0; background: white; padding: 10px;">
  <h1>
    Projects
  </h1>

  <a href="#newDocument" data-url="<%= new_document_path(:user_id => current_user.id)%>" data-toggle="modal" class="new-document-button"><i class="icon-plus"></i> New document</a>

  <ul class="tasks zebra-list">
    <% if @document.count > 0 %>
      <% @document.each do |document| %>
      <li>
        <input type="checkbox"> 
        <span class="title"><%= link_to document.title, document %> 
        </span> 
        <span class="meta">Created <em><%=time_ago_in_words(document.created_at)%></em> ago by <em><%=document.user.name%></em></span>
      </li>
      <% end %>
    <% end %>
  </ul>
</div>

<!-- Modal -->
<div id="newDocument" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>New Document</h3>
  </div>
  <div class="modal-body">
    Carregando...
  </div>
</div>

app/views/documents/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Judi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/manager.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= initjs_tag app_name: 'Tasker' %>

<%= render "shared/navbar"%>

<div class="container">

  <div class="row" style="padding-top: 40px">
    <%= render "shared/sidebar"%>

    <div class="span10">
      <%= yield %>
    </div>
    
  </div>
</div>

</body>
</html>

app/views/projects/_documents.html.erb
<div style="padding-top: 8px">
  <ul class="tasks zebra-list">

    <% @project.documents.each do |doc| %>
    <li>
      <input type="checkbox"> 
      <span class="title"><%= link_to doc.name, doc %> 
        <div style="float: right">
          <%= link_to icon(:edit, :white) + ' Edit', "#editProject", :data => { :url => edit_project_path(@project), :toggle => "modal" }, :class => "edit-project-button btn btn-primary" %>  
          <%= link_to icon(:remove , :white) + ' Remove', doc, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger" %>
        </div>
     </span> 
     <span class="meta">Created <em><%=time_ago_in_words(doc.created_at)%></em> ago by <em><%=doc.project.user.name%></em></span>
   </li>
   <% end %>
 </ul>
</div>

<a href="#" class="btn btn-small"><i class="icon-pencil icon-white"></i> </a>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.hidden_field :user_id %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.input :description, :as => :ckeditor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_newprojectform.html.erb
<a class="toggle-link" href="#new-project"><i class="icon-plus"></i> New Project</a>

<%= simple_form_for Project.new,  :html => { :class => 'form-horizontal hidden' , :id => 'new-project' } do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= notification %>
    </div>
  <% end %>

  <legend>New Project</legend>
  <%= f.input :title, :input_html => { :class => "span3" },
  :hint => "add your project title here" %>


  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
  </div>

<% end %>

app/views/projects/_tasks.html.erb
<div id="subtasks" style="padding-top: 8px">
  <table class="table table-striped table-condensed table-bordered">
    <tbody>
      <% @project.tasks.roots.order("priority asc").each do |subtask| %>
      <tr data-contact="<%= subtask.id %>" href-contact="<%= details_task_path(subtask) %>">
        <td class="tasks-prio prio<%= subtask.priority.value %>"></td>
        <td class=""></td>
        <td class="">
          <input type="checkbox">
        </td>
        <td>
          <span class="title"><%= link_to subtask.title, subtask %></span> 
          <span class="meta">Created <em><%=time_ago_in_words(subtask.created_at)%></em> ago by <em><%=subtask.project.user.name%></em></span>
        </td> 
        <td class="">Apr 28</td>
        <td class=""></td></tr>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="well" style="padding: 8px 0; background: white; padding: 10px;">
  <h1>
    Projects
  </h1>

  <a href="#newProject" data-url="<%= new_project_path(:user_id => current_user.id)%>" data-toggle="modal" class="new-project-button"><i class="icon-plus"></i> New Project</a>

  <ul class="tasks zebra-list">
    <% if @projects.count > 0 %>
      <% @projects.each do |project| %>
      <li>
        <input type="checkbox"> 
        <span class="title"><%= link_to project.title, project %> 
        </span> 
        <span class="meta">Created <em><%=time_ago_in_words(project.created_at)%></em> ago by <em><%=project.user.name%></em></span>
      </li>
      <% end %>
    <% end %>
  </ul>

  <div id="tools">
    <a href="#" class="btn"><i class="icon-folder-open"></i> Archive</a>

    <a href="#" class="btn btn-success pull-right spaced"><i class="icon-plus icon-white"></i> New Project</a>

    <div class="btn-group pull-right spaced" >
      <button class="btn span2">Sort By</button>
      <button class="btn dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
      <ul class="dropdown-menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li><a href="#">Separated link</a></li>
      </ul>
    </div>

    <div class="input-append pull-right spaced">
      <input class="span3" id="appendedInputButton" type="text" value="Filter by..."></input>
      <button class="btn" type="button">Filter!</button>
    </div>

  </div>

  <div id="projects">
    <table class="table">
      <tbody>
        <tr>
          <td>
            01
            <i class="icon-star"></i>
            <i class="icon-star"></i>
            <i class="icon-star-empty"></i>
          </td>
          <td>
            <img src="http://www.rocstarr.com/Tipapalooza/files/tipapalooza-icon-100x100.png" alt="ALT NAME">
          </td>
          <td>
            <h2>
              Gerenciador de tarefas
            </h2>
            <b> Created: </b>
            June 17 2012
            |
            <b> Status: </b>
            running
          </td>
          <td>
            <a href="#" class="btn btn-primary"> Open Project</a>
            <a href="#" class="btn">
              <i class="icon-edit"></i> Edit</a>                
            </td>
          </tr>
          <tr>
            <td>
              02
              <i class="icon-star"></i>
              <i class="icon-star-empty"></i>
              <i class="icon-star-empty"></i>
            </td>
            <td>
              <img src="http://www.tinywonderstudios.com/gfx/press/pixi_icon_100x100.png" alt="ALT NAME">
            </td>
            <td>
              <h2>
                Controle de gasto de combustivel
              </h2>
              <b> Created: </b>
              January 03 2013
              |
              <b> Status: </b>
              running
            </td>
            <td>
              <a href="#" class="btn btn-primary"> Open Project</a>
              <a href="#" class="btn">
                <i class="icon-edit"></i> Edit</a>                
              </td>
            </tr>
            <tr>
              <td>
                03
                <i class="icon-star"></i>
                <i class="icon-star-empty"></i>
                <i class="icon-star-empty"></i>
              </td>
              <td>
                <img src="http://upload.wikimedia.org/wikipedia/de/8/8b/Brights_icon_100x100.gif" alt="ALT NAME">
              </td>
              <td>
                <h2>
                  Controle de orçamento pessoal
                </h2>
                <b> Created: </b>
                March 25 2013
                |
                <b> Status: </b>
                running
              </td>
              <td>
                <a href="#" class="btn btn-primary"> Open Project</a>
                <a href="#" class="btn">
                  <i class="icon-edit"></i> Edit</a>                
                </td>
              </tr>
            </tbody>
          </table>
        </div>

</div>

<!-- Modal -->
<div id="newProject" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>New Project</h3>
  </div>
  <div class="modal-body">
    Carregando...
  </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="span7" style="margin: 0;">
  <div class="well" style="padding: 8px 0; background: white; padding: 10px;">
    <%= link_to 'Edit', "#editProject", :data => { :url => edit_project_path(@project), :toggle => "modal" }, :class => "edit-project-button" %> |
    <%= link_to 'Back', projects_path %>
    <h1>
      <%= @project.title %>  
    </h1>


    <ul id="myTab" class="nav nav-tabs">
      <li class="active"><a href="#tasks" data-toggle="tab">Tasks</a></li>
      <li class=""><a href="#description" data-toggle="tab">Description</a></li>            
      <li class=""><a href="#files" data-toggle="tab">Attached Files</a></li>            
      <li class=""><a href="#history" data-toggle="tab">History</a></li>

    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade  active in" id="tasks">

        <a href="#newTask" data-url="<%= new_task_path(:project_id => @project.id)%>" data-toggle="modal" class="new-task-button"><i class="icon-plus"></i> New Task</a>
        
        <% if @project.have_tasks? %>
        <%= render "tasks" %>
        <% end %>

        <h3>
          Completed Tasks
        </h3>
        <ul class="tasks done">
          <li>
            <i class="icon-ok"></i> <span class="title">Wash the Car</span> <span class="meta">Completed <em>2 days ago</em> by <em>John</em></span>
          </li>
          <li>
            <i class="icon-ok"></i> <span class="title">Call the plumber</span> <span class="meta">Completed <em>5 days ago</em> by <em>John</em></span>
          </li>
          <li>
            <i class="icon-ok"></i> <span class="title">Try that new cookie recipe</span> <span class="meta">Completed <em>2 weeks ago</em> by <em>Jill</em></span>
          </li>
        </ul>
      </div>
      <div class="tab-pane fade" id="description">
        <p><%= raw @project.description %></p>
      </div>
      <div class="tab-pane fade" id="files">
        <a href="#newDocument" data-url="<%= new_document_path(:project_id => @project.id)%>" data-toggle="modal" class="new-document-button"><i class="icon-plus"></i> New Document</a>
        <% if @project.have_documents? %>
          <%= render "documents" %>
        <% end %>
      </div>
      <div class="tab-pane fade" id="history">
        <table class="table table-striped table-condensed table-bordered">
          <thread>
            <tr>
              <th>Time</th>
              <th>Description</th>
              <th>Status</th>
            </tr>
          </thread>
          <tbody>
            <tr>
              <td>25/02/2013 00:03:02</td>
              <td>Iniciados os trabalhos na tarefa</td> 
              <td align=right; width=50px;> <span class="label label-info">Iniciada</span> </td>
            </tr>

            <tr>
              <td>25/02/2013 00:07:02</td>
              <td>Aguardando cliente - Falta definicao de cores</td> 
              <td align=right; width=50px;><span class="label label-warning">Aguardando</span> </td>
            </tr>

            <tr>
              <td>25/02/2013 00:13:02</td>
              <td>Reiniciados os trabalhos na tarefa</td> 
              <td align=right; width=50px;><span class="label label-info">Trabalhando</span> </td>
            </tr>

            <tr>
              <td>25/02/2013 00:20:02</td>
              <td>Finalizados os trabalhos na tarefa</td> 
              <td align=right; width=50px;> <span class="label label-success">Terminada</span>  </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render "shared/statusbar"%>

 
<!-- Modal -->
<div id="newTask" class="span7 modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>New Task</h3>
  </div>
  <div class="modal-body">
    Carregando...
  </div>
</div>

<div id="editProject" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Editing Project</h3>
  </div>
  <div class="modal-body">
    Carregando...
  </div>
</div>

<div id="newDocument" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>New Document</h3>
  </div>
  <div class="modal-body">
    Carregando...
  </div>
</div>

app/views/shared/_breadcrumb.html.erb
<ul class="breadcrumb">
  <li><b><%= link_to "Project: " +  @task.project.title, @task.project %> </b> <span class="divider">/</span> </li>
  <% for ancestor in @task.ancestors do %>
  <li><%= link_to ancestor.title, ancestor %> <span class="divider">/</span></li>
  <% end %>
</ul>

app/views/shared/_mainscreen.html.erb
<%= render "shared/navbar"%>

<div class="container">

  <div class="row" style="padding-top: 40px">
    <%= render "shared/sidebar"%>

    <div class="span10">
      <%= yield %>
    </div>

    
  </div>
</div>

app/views/shared/_sidebar.html.erb
      <div class="span2" style="">
        <div class="well" style="padding: 8px 0;">
          <ul class="nav nav-list">
            <li class="nav-header">
              Tasker
            </li>
            <li>
              <a href="index.htm"><i class="icon-home"></i> Dashboard</a>
            </li>
            <li>
              <a href="/projects"><i class="icon-folder-open"></i> Projects</a>
            </li>
            <li class="divider">
            </li>
            <li class="nav-header">
              Project
            </li>
            <li>
              <a href="index.htm"><i class="icon-tasks"></i> Dashboard</a>
            </li>
            <li>
              <a href="tasks.htm"><i class="icon-check"></i> Tasks</a>
            </li>
            <li>
              <a href="files.htm"><i class="icon-file"></i> Files</a>
            </li>
            <li>
              <a href="activity.htm"><i class="icon-list-alt"></i> Activity</a>
            </li>
           
            <li class="divider">
            </li>
            <li>
              <a href="help.htm"><i class="icon-info-sign"></i> Help</a>
            </li>
            <li class="nav-header">
              Bonus Templates
            </li>
            <li>
              <a href="gallery.htm"><i class="icon-picture"></i> Gallery</a>
            </li>
            <li>
              <a href="blank.htm"><i class="icon-stop"></i> Blank Slate</a>
            </li>
          </ul>
        </div>
      </div>

app/views/tasks/_task.html.erb


  <div class="task">
    <div class="created_at"><%= task.created_at.strftime("%B %d, %Y") %></div>
    <div class="content">
      <%= task.title %>
    </div>
    <div class="actions">
      <%= link_to "Reply", new_task_path(:parent_id => task, :project_id => task.project) %> |
      <%= link_to "Destroy", task, :confirm => "Are you sure?", :method => :delete %>
    </div>
  </div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb


<div class="row-fluid">

<div class="span4 offset1">

<h1>Listing tasks</h1>


<%= nested_tasks @tasks %>


<span class="label label-success">Success</span>

<br>

<%= link_to 'New task', new_task_path(project_id: params[:project_id]) %>
</div>


</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render @task.parent if @task.parent %>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<%= render "shared/breadcrumb"%>
<div class="span7" style="margin: 0;">
  <div class="well" style="padding: 8px 0; background: white; padding: 10px;">

    <%= link_to 'Edit', "#editTask", :data => { :url => edit_task_path(@task), :toggle => "modal" }, :class => "edit-task-button" %> |
    <% if @task.parent %>
      <%= link_to 'Back', @task.parent %>
    <% else %>
      <%= link_to 'Back', @task.project %>
    <% end %>
    <h1>
      <%= @task.title %>  
    </h1>


    <ul id="myTab" class="nav nav-tabs">
      <li class="active"><a href="#tasks" data-toggle="tab">Tasks</a></li>
      <li class=""><a href="#description" data-toggle="tab">Description</a></li>            
      <li class=""><a href="#files" data-toggle="tab">Attached Files</a></li>            
      <li class=""><a href="#history" data-toggle="tab">History</a></li>

    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade  active in" id="tasks">
        
        <a href="#newTask" data-url="<%= new_task_path(:parent_id => @task.id, :project_id => @task.project.id)%>" data-toggle="modal" class="new-task-button"><i class="icon-plus"></i> New Task</a>

        <% if @task.have_subtasks? %>
        <%= render "subtasks" %>
        <% end %>

        <h3>
          Completed Tasks
        </h3>
        <ul class="tasks done">
          <li>
            <i class="icon-ok"></i> <span class="title">Wash the Car</span> <span class="meta">Completed <em>2 days ago</em> by <em>John</em></span>
          </li>
          <li>
            <i class="icon-ok"></i> <span class="title">Call the plumber</span> <span class="meta">Completed <em>5 days ago</em> by <em>John</em></span>
          </li>
          <li>
            <i class="icon-ok"></i> <span class="title">Try that new cookie recipe</span> <span class="meta">Completed <em>2 weeks ago</em> by <em>Jill</em></span>
          </li>
        </ul>
      </div>
      <div class="tab-pane fade" id="description">
        <p><%= raw @task.description %></p>
      </div>
      <div class="tab-pane fade" id="files">
        <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
      </div>
      <div class="tab-pane fade" id="history">
        <table class="table table-striped table-condensed table-bordered">
          <thread>
            <tr>
              <th>Time</th>
              <th>Description</th>
              <th>Status</th>
            </tr>
          </thread>
          <tbody>
            <tr>
              <td>25/02/2013 00:03:02</td>
              <td>Iniciados os trabalhos na tarefa</td> 
              <td align=right; width=50px;> <span class="label label-info">Iniciada</span> </td>
            </tr>

            <tr>
              <td>25/02/2013 00:07:02</td>
              <td>Aguardando cliente - Falta definicao de cores</td> 
              <td align=right; width=50px;><span class="label label-warning">Aguardando</span> </td>
            </tr>

            <tr>
              <td>25/02/2013 00:13:02</td>
              <td>Reiniciados os trabalhos na tarefa</td> 
              <td align=right; width=50px;><span class="label label-info">Trabalhando</span> </td>
            </tr>

            <tr>
              <td>25/02/2013 00:20:02</td>
              <td>Finalizados os trabalhos na tarefa</td> 
              <td align=right; width=50px;> <span class="label label-success">Terminada</span>  </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render "shared/statusbar"%>

<p id="notice"><%= notice %></p>

<!-- Modal -->
<div id="editTask" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Editing Task</h3>
  </div>
  <div class="modal-body">
    Carregando...
  </div>
</div>

<div id="newTask" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>New Task</h3>
  </div>
  <div class="modal-body">
    Carregando...
  </div>
</div>